# Generated by Django 6.0.1 on 2026-03-10 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0010_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('g', 'Gram'), ('ml', 'Ml'), ('item', 'Cái')], default='g', max_length=10)),
                ('quantity', models.FloatField(default=0)),
                ('min_quantity', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_type', models.CharField(choices=[('finished', 'Thành phẩm'), ('material', 'Nguyên vật liệu')], max_length=20)),
                ('action', models.CharField(choices=[('import', 'Nhập kho'), ('export', 'Xuất kho'), ('make', 'Pha chế'), ('order', 'Bán hàng')], max_length=20)),
                ('quantity', models.FloatField(default=0)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafe.rawmaterial')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafe.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.product')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafe.rawmaterial')),
            ],
            options={
                'unique_together': {('product', 'material')},
            },
        ),
    ]
