# Generated by Django 6.0.1 on 2026-03-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0011_rawmaterial_stocklog_productrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('preparing', 'Đang pha chế'), ('completed', 'Hoàn tất'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
