# Generated by Django 6.0.1 on 2026-03-17 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0014_order_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafebranch',
            name='delivery_radius',
            field=models.FloatField(default=3000),
        ),
        migrations.AddField(
            model_name='cafebranch',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cafebranch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='branches/'),
        ),
        migrations.AddField(
            model_name='cafebranch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cafebranch',
            name='open_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cafebranch',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafe.cafebranch'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_distance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('not_required', 'Không áp dụng'), ('waiting', 'Chờ giao'), ('shipping', 'Đang giao'), ('delivered', 'Đã giao'), ('failed', 'Giao thất bại')], default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('dine_in', 'Tại quán'), ('takeaway', 'Mang đi'), ('delivery', 'Giao hàng')], default='takeaway', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('preparing', 'Đang pha chế'), ('delivering', 'Đang giao'), ('completed', 'Hoàn tất'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
    ]
