# Generated by Django 6.0.1 on 2026-03-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0015_cafebranch_delivery_radius_cafebranch_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
