# Generated by Django 6.0.1 on 2026-03-20 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0018_customerprofile_reservation_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.cafebranch', verbose_name='Áp dụng chi nhánh'),
        ),
    ]
