# Generated by Django 6.0.1 on 2026-03-21 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0021_reservation_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cafe.cafebranch'),
        ),
    ]
