# Generated by Django 6.0.1 on 2026-03-21 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0022_table_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafe.order'),
        ),
    ]
