# Generated by Django 6.0.1 on 2026-04-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0024_supplier_supplierorder_workshift_shiftassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('cashier', 'Thu ngân'), ('shipper', 'Giao hàng'), ('customer', 'Khách hàng')], default='customer', max_length=20),
        ),
    ]
