# Generated by Django 6.0.1 on 2026-04-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0025_add_role_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email khách hàng'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email khách hàng'),
        ),
    ]
