# Generated by Django 6.0.1 on 2026-04-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0027_order_accepted_at_order_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='hold_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('confirmed', 'Đã xác nhận'), ('seated', 'Khách đã nhận bàn'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy'), ('expired', 'Hết hạn giữ bàn')], default='pending', max_length=20),
        ),
    ]
