# Generated by Django 6.0.1 on 2026-04-09 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0028_reservation_hold_expires_at_alter_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklog',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafe.cafebranch'),
        ),
        migrations.CreateModel(
            name='BranchMaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0)),
                ('min_quantity', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_stocks', to='cafe.cafebranch')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='cafe.rawmaterial')),
            ],
            options={
                'unique_together': {('material', 'branch')},
            },
        ),
    ]
