# Generated by Django 6.0.1 on 2026-04-15 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0029_stocklog_branch_branchmaterialstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('confirmed', 'Đã xác nhận'), ('preparing', 'Đang pha chế'), ('ready_for_delivery', 'Chờ lấy hàng'), ('delivering', 'Đang giao'), ('completed', 'Hoàn tất'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='ShipperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Số điện thoại')),
                ('is_available', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('max_active_orders', models.IntegerField(default=5, verbose_name='Số đơn tối đa cùng lúc')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shippers', to='cafe.cafebranch')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipper_profile', to='cafe.user')),
            ],
            options={
                'verbose_name': 'Shipper',
                'verbose_name_plural': 'Shipper Profiles',
            },
        ),
    ]
