# Generated by Django 6.0.1 on 2026-04-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0030_alter_order_status_shipperprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripe Checkout Session ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('stripe', 'Stripe')], default='cash', max_length=10),
        ),
    ]
